myblog/myblog/apps/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='home'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment', views.leave_comment, name='leave_comment'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('/grappelli', include('grappelli.urls')),
    path('', include('articles.urls')),
    path('admin/', admin.site.urls),
]

myblog/myblog/apps/articles/models.py
from django.db import models
import datetime
from django.utils import timezone

class Article(models.Model):
    article_title = models.CharField('Title name', max_length=200)
    article_text = models.TextField('Title text')
    pub_date = models.DateTimeField('publication date')

    def __str__(self):
    	return self.article_title

    def was_published_recently(self):
    	return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))

    def text_preveiw(self):
        return_text = self.article_text.split('.')[0]
        return return_text + ' ...'

class Comment(models.Model):
    parent_article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField("Author's name", max_length=50)
    comment_text = models.CharField('Comment text', max_length=300)

    def __str__(self):
    	return self.author_name

myblog/myblog/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from .models import Article, Comment

def index(request):
	latest_articles_list = Article.objects.order_by('-pub_date')[:5]
	return render(request, 'articles/list.html', {"articles_list": latest_articles_list})


def detail(request, article_id):
	try:
		article = Article.objects.get( id = article_id )
	except:
		raise Http404("Статья не найдена )= ")

	return render(request, 'articles/detail.html', {'article': article})

def leave_comment(request, article_id):
	pass

myblog/myblog/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Последние статьи{% endblock %}

{% block content %}

	<div class="container">
		<br>
		<h2>Статьи моего блога</h2>
		<br>
		<br>


	{% if articles_list %}

		<div class="card-deck">

		{% for article in articles_list %}

			<div class="card">
			  <div class="card-body">
			    <h5 class="card-title">{{article.article_title}}</h5>
			    <p class="card-text">{{article.text_preveiw}}</p>
			    <a href="{% url 'articles:detail' article.id %}" class="btn btn-primary stretched-link">Читать далее</a>
			  </div>
			</div>

		{% endfor %}

		</div>

	{% else %}
		Статьи не найдены )=
	{% endif %}

	</div>

{% endblock %}

myblog/myblog/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<title>{% block title %} {% endblock %}</title>
	<style>
		.card-deck{
			flex-wrap: wrap;
		}
		.card{
			margin-bottom: 30px;
			min-width: 300px;
			max-width: 30.7%;
			
		}
	</style>
</head>
<body>
	{% block content %} {% endblock %}
</body>
</html>